
import React from 'react';
import { 
  Cloud, 
  Info, 
  Check, 
  Zap, 
  Layers, 
  Server, 
  Terminal, 
  ChevronDown, 
  X, 
  RefreshCw, 
  Cpu,
  Moon,
  Sun,
  Copy,
  MapPin,
  Globe,
  AlertTriangle,
  Search,
  Trash2,
  Code2,
  FileText,
  ArrowUp,
  ChevronRight,
  CheckCircle,
  AlertCircle,
  PieChart,
  BarChart2,
  Sparkles,
  Database,
  HardDrive,
  BookOpen,
  Sliders,
  DollarSign,
  ArrowLeft,
  History,
  ArrowDown,
  Plus,
  ChevronUp,
  Play,
  Key,
  Link,
  ExternalLink
} from 'lucide-react';

export const Icons = {
  Cloud: (props: any) => <Cloud size={20} {...props} />,
  Info: (props: any) => <Info size={16} {...props} />,
  Check: (props: any) => <Check size={16} {...props} />,
  Bolt: (props: any) => <Zap size={16} {...props} />,
  Layers: (props: any) => <Layers size={16} {...props} />,
  Server: (props: any) => <Server size={16} {...props} />,
  Terminal: (props: any) => <Terminal size={16} {...props} />,
  ChevronDown: (props: any) => <ChevronDown size={14} {...props} />,
  ChevronUp: (props: any) => <ChevronUp size={14} {...props} />,
  ChevronRight: (props: any) => <ChevronRight size={14} {...props} />,
  Cancel: (props: any) => <X size={16} {...props} />,
  Refresh: (props: any) => <RefreshCw size={16} {...props} />,
  Chip: (props: any) => <Cpu size={14} {...props} />,
  Cpu: (props: any) => <Cpu size={14} {...props} />,
  Moon: (props: any) => <Moon size={16} {...props} />,
  Sun: (props: any) => <Sun size={16} {...props} />,
  Copy: (props: any) => <Copy size={12} {...props} />,
  MapPin: (props: any) => <MapPin size={14} {...props} />,
  Globe: (props: any) => <Globe size={14} {...props} />,
  Alert: (props: any) => <AlertTriangle size={16} {...props} />,
  AlertTriangle: (props: any) => <AlertTriangle size={16} {...props} />,
  Search: (props: any) => <Search size={14} {...props} />,
  Trash: (props: any) => <Trash2 size={14} {...props} />,
  Code: (props: any) => <Code2 size={14} {...props} />,
  FileText: (props: any) => <FileText size={14} {...props} />,
  ArrowUp: (props: any) => <ArrowUp size={16} {...props} />,
  ArrowDown: (props: any) => <ArrowDown size={16} {...props} />,
  ArrowLeft: (props: any) => <ArrowLeft size={16} {...props} />,
  CheckCircle: (props: any) => <CheckCircle size={16} {...props} />,
  History: (props: any) => <History size={16} {...props} />,
  AlertCircle: (props: any) => <AlertCircle size={16} {...props} />,
  PieChart: (props: any) => <PieChart size={16} {...props} />,
  BarChart2: (props: any) => <BarChart2 size={16} {...props} />,
  Sparkles: (props: any) => <Sparkles size={16} {...props} />,
  Database: (props: any) => <Database size={14} {...props} />,
  HardDrive: (props: any) => <HardDrive size={14} {...props} />,
  Book: (props: any) => <BookOpen size={16} {...props} />,
  BookOpen: (props: any) => <BookOpen size={16} {...props} />,
  Sliders: (props: any) => <Sliders size={16} {...props} />,
  DollarSign: (props: any) => <DollarSign size={16} {...props} />,
  Plus: (props: any) => <Plus size={16} {...props} />,
  Play: (props: any) => <Play size={16} {...props} />,
  Zap: (props: any) => <Zap size={16} {...props} />,
  Key: (props: any) => <Key size={16} {...props} />,
  X: (props: any) => <X size={16} {...props} />,
  Link: (props: any) => <Link size={14} {...props} />,
  ExternalLink: (props: any) => <ExternalLink size={14} {...props} />
};
